# Free keys (fast to get)
FRED_API_KEY = "YOUR_FRED_KEY"         # free from fred.stlouisfed.org
EIA_API_KEY  = "YOUR_EIA_KEY"          # free from api.eia.gov
ODDS_API_KEY = ""                      # (optional) the-odds-api.com free/pro
# If you later add paid feeds, stick them here too (Polygon, Finnhub, etc.)
# Gateway Configuration
GATEWAY_URL = "https://crypto-hybrid-live.onrender.com"
GATEWAY_KEY = "change-this-to-a-strong-secret"
https://crypto-hybrid-live-1.onrender.com
