# ===== Hybrid Intelligence Systems Config =====

# Gateway Connection
GATEWAY_URL = "https://his-gateway.onrender.com"

# Environment Info
ENV = "production"
SERVICE = "HIS-UI"
OWNER = "Jesse Ray Landingham Jr"
