# =============================================================
#  Streamlit Secrets File
#  Environment configuration for Render or local use.
# =============================================================

# ---- API Keys (replace with your real ones or keep placeholders) ----
FRED_API_KEY = "demo-fred-key"          # from https://fred.stlouisfed.org
EIA_API_KEY = "demo-eia-key"            # from https://api.eia.gov
ODDS_API_KEY = "demo-odds-key"          # optional: from https://the-odds-api.com

# ---- Gateway Connection ----
GATEWAY_URL = "https://crypto-hybrid-live-1.onrender.com"
HIS_KEY = "punchlogic-his-master"

# ---- Environment Info ----
ENV = "production"
SERVICE = "HIS-Gateway"
OWNER = "Jesse Ray Landingham Jr"
