# Streamlit Secrets File for Production
# =====================================

# Gateway URL (your live backend)
GATEWAY_URL = "https://crypto-hybrid-live-1.onrender.com"

# API Keys (replace if needed)
FRED_API_KEY = "demo-fred"
EIA_API_KEY = "demo-eia"
ODDS_API_KEY = "demo-odds"

# Meta info
ENV = "production"
SERVICE = "CRYPTO-HYBRID-LIVE"
OWNER = "Jesse Ray Landingham"
